services:
  - type: web
    name: collecte-taxe-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/collecte-taxe/browser
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
