services:
  - type: web
    name: collecte-taxe-frontend
    env: static

    # Pas de rootDir

    buildCommand: cd frontend/frontend && npm install && npm run build

    staticPublishPath: frontend/frontend/dist/collecte-taxe/browser/browser


    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      - key: NODE_VERSION
        value: 20