services:
  - type: web
    name: collecte-taxe-frontend
    env: static

    rootDir: frontend/frontend

    buildCommand: npm install && npm run build && ls -la dist/ && ls -la dist/collecte-taxe/ && ls -la dist/collecte-taxe/browser/

    # Le chemin est relatif au rootDir (frontend/frontend)
    staticPublishPath: dist/collecte-taxe/browser

    # Ajoutez ces r√®gles de redirection
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      - key: NODE_VERSION
        value: 20