services:
  - type: web
    name: collecte-taxe-frontend
    env: static

    rootDir: frontend/frontend

    buildCommand: npm install && npm run build

    staticPublishPath: dist/collecte-taxe/browser

    envVars:
      - key: NODE_VERSION
        value: 20
